
# Site
title: MDP.Net

# theme
remote_theme: pmarsceill/just-the-docs
aux_links:
  "MDP.Net on GitHub":
    - "//github.com/Clark159/MDP.Net"
search_enabled: false
favicon_ico: "/Pages/favicon.ico"
color_scheme: dark
